//Function migration (image list to matrix) for: applycform
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = rgb2lab(varargin)
	select length(varargin)
		case 01 then
			res = il2mat(raw_rgb2lab(mat2il(varargin(01))))
		else
			error(39)
	end
endfunction
