//Function migration (image list to matrix) for: applycform
//Generated by migrate.cpp
//Author: Anirudh Katoch
function res = roipoly(varargin)
	select length(varargin)
		case 03 then
			res = il2mat(raw_roipoly(mat2il(varargin(01)), varargin(02),(varargin(03))))
		else
			error(39)
	end
endfunction
